server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
    #instance:
    # lease-renewal-interval-in-seconds: 10


#  instance:
#    prefer-ip-address: true
#    ip-address: 192.168.100.4
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

#serviceUrl:
 # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

